CREATE TABLE public.savings_goals (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  title text not null,
  category text not null default 'outros',
  target_amount numeric not null check (target_amount > 0),
  saved_amount numeric not null default 0 check (saved_amount >= 0),
  target_date date,
  color text not null default '#8b5cf6',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.savings_goals TO authenticated;
GRANT ALL ON public.savings_goals TO service_role;

ALTER TABLE public.savings_goals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "goals_select_own" ON public.savings_goals FOR SELECT TO authenticated USING (auth_user_id = auth.uid());
CREATE POLICY "goals_insert_own" ON public.savings_goals FOR INSERT TO authenticated WITH CHECK (auth_user_id = auth.uid());
CREATE POLICY "goals_update_own" ON public.savings_goals FOR UPDATE TO authenticated USING (auth_user_id = auth.uid()) WITH CHECK (auth_user_id = auth.uid());
CREATE POLICY "goals_delete_own" ON public.savings_goals FOR DELETE TO authenticated USING (auth_user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_savings_goals_updated_at
BEFORE UPDATE ON public.savings_goals
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();